leafcn: fates_leaf_vcmax25top
dleaf: fates_turb_leaf_diameter
fnps: fates_leaf_fnps
jmaxha: fates_leaf_jmaxha
jmaxhd: fates_leaf_jmaxhd
jmaxse_sf: fates_leaf_jmaxse
medlynintercept: fates_leaf_stomatal_intercept
medlynslope: fates_leaf_stomatal_slope_medlyn
rholnir: fates_rad_leaf_rhonir
rholvis: fates_rad_leaf_rhovis
rhosnir: fates_rad_stem_rhonir
rhosvis: fates_rad_stem_rhovis
slatop: fates_leaf_slatop
smpsc: fates_nonhydro_smpsc
smpso: fates_nonhydro_smpso
taulnir: fates_rad_leaf_taunir
taulvis: fates_rad_leaf_tauvis
tausnir: fates_rad_stem_taunir
tausvis: fates_rad_stem_tauvis
vcmaxha: fates_leaf_vcmaxha
vcmaxhd: fates_leaf_vcmaxhd
vcmaxse_sf: fates_leaf_vcmaxse